import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link";
import "./globals.css";
import { publicApi, publicApiConfig } from "./lib/publicApi";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const site = await publicApi.site();
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col bg-white text-zinc-900">
        <header className="border-b bg-white">
          <div className="mx-auto flex w-full max-w-6xl items-center justify-between px-6 py-4">
            <div className="text-lg font-semibold">
              {site?.name ?? "Client Website"}
            </div>
            <nav className="flex flex-wrap gap-4 text-sm">
              <Link href="/">Home</Link>
              <Link href="/about">About</Link>
              <Link href="/services">Services</Link>
              <Link href="/blog">Blog</Link>
              <Link href="/contact">Contact</Link>
            </nav>
          </div>
        </header>
        {!publicApiConfig.API_KEY ? (
          <div className="mx-auto w-full max-w-4xl px-6 py-6 text-sm text-red-600">
            Missing `NEXT_PUBLIC_TENANT_API_KEY` in the template environment. Add it to load
            public content.
          </div>
        ) : null}
        <main className="mx-auto flex w-full max-w-6xl flex-1 flex-col gap-10 px-6 py-10">
          {children}
        </main>
        <footer className="border-t bg-white py-6 text-center text-xs text-zinc-500">
          © {new Date().getFullYear()} {site?.name ?? "Client Website"}.
        </footer>
      </body>
    </html>
  );
}
